language: cpp

compiler:
  - gcc

before_install:
  # g++4.9
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcap-dev

install:
  # g++4.9
  - if [ "$CXX" = "g++" ]; then sudo apt-get update && sudo apt-get install -qq g++-4.9 gcc-4.9 cpp-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

before_script:
  - cmake -G "Unix Makefiles"

script: 
  - $CXX --version
  - make

notifications:
  recipients:
    - jeffk@jdkoftinoff.com
  email:
    on_success: change
    on_failure: always

os:
  - linux

